export const LANGUAGES = [
    { code: 'en', name: 'English', countryCode: 'us' },
    { code: 'es', name: 'Spanish', countryCode: 'es' },
    { code: 'fr', name: 'French', countryCode: 'fr' },
    { code: 'de', name: 'German', countryCode: 'de' },
    { code: 'it', name: 'Italian', countryCode: 'it' },
    { code: 'ja', name: 'Japanese', countryCode: 'jp' },
    { code: 'ko', name: 'Korean', countryCode: 'kr' },
    { code: 'zh', name: 'Chinese', countryCode: 'cn' },
    { code: 'cn', name: 'Chinese (Legacy)', countryCode: 'cn' },
    { code: 'ru', name: 'Russian', countryCode: 'ru' },
    { code: 'pt', name: 'Portuguese', countryCode: 'br' },
    { code: 'ar', name: 'Arabic', countryCode: 'sa' },
    { code: 'fa', name: 'Persian', countryCode: 'ir' },
    { code: 'nl', name: 'Dutch', countryCode: 'nl' },
    { code: 'sv', name: 'Swedish', countryCode: 'se' },
    { code: 'tr', name: 'Turkish', countryCode: 'tr' },
    { code: 'pl', name: 'Polish', countryCode: 'pl' },
    { code: 'el', name: 'Greek', countryCode: 'gr' },
    { code: 'he', name: 'Hebrew', countryCode: 'il' },
    { code: 'no', name: 'Norwegian', countryCode: 'no' },
    { code: 'la', name: 'Latin', countryCode: 'va' },
    { code: 'ca', name: 'Catalan', countryCode: 'ad' },
    { code: 'cs', name: 'Czech', countryCode: 'cz' },
    { code: 'fi', name: 'Finnish', countryCode: 'fi' },
    { code: 'ro', name: 'Romanian', countryCode: 'ro' },
    { code: 'da', name: 'Danish', countryCode: 'dk' },
    { code: 'uk', name: 'Ukrainian', countryCode: 'ua' },
    { code: 'id', name: 'Indonesian', countryCode: 'id' },
    { code: 'zh-t', name: 'Chinese (Trad)', countryCode: 'tw' },
    { code: 'hk', name: 'Cantonese', countryCode: 'hk' },
    { code: 'srp', name: 'Serbian', countryCode: 'rs' },
    { code: 'is', name: 'Icelandic', countryCode: 'is' },
    { code: 'vi', name: 'Vietnamese', countryCode: 'vn' },
    { code: 'sl', name: 'Slovenian', countryCode: 'si' },
    { code: 'ka', name: 'Georgian', countryCode: 'ge' },
    { code: 'hi', name: 'Hindi', countryCode: 'in' },
    { code: 'sw', name: 'Swahili', countryCode: 'ke' },
    { code: 'mk', name: 'Macedonian', countryCode: 'mk' },
    { code: 'km', name: 'Khmer', countryCode: 'kh' },
    { code: 'af', name: 'Afrikaans', countryCode: 'za' },
    { code: 'pa', name: 'Punjabi', countryCode: 'in' },
    { code: 'ga', name: 'Irish Gaelic', countryCode: 'ie' },
    { code: 'th', name: 'Thai', countryCode: 'th' },
    { code: 'ur', name: 'Urdu', countryCode: 'pk' },
    { code: 'eo', name: 'Esperanto', countryCode: 'un' },
    { code: 'sk', name: 'Slovak', countryCode: 'sk' },
    { code: 'ms', name: 'Malay', countryCode: 'my' },
    { code: 'gu', name: 'Gujarati', countryCode: 'in' },
    { code: 'bg', name: 'Bulgarian', countryCode: 'bg' },
    { code: 'be', name: 'Belarusian', countryCode: 'by' },
    { code: 'hrv', name: 'Croatian', countryCode: 'hr' },
    { code: 'hu', name: 'Hungarian', countryCode: 'hu' },
    { code: 'hy', name: 'Armenian', countryCode: 'am' },
    { code: 'tl', name: 'Tagalog', countryCode: 'ph' }
];

export const LANG_MAP: Record<string, { name: string; countryCode: string }> = LANGUAGES.reduce((acc, lang) => {
    acc[lang.code] = { name: lang.name, countryCode: lang.countryCode };
    return acc;
}, {} as Record<string, { name: string; countryCode: string }>);
